# #######################################################################################
# HYPR CONFIG
# #######################################################################################

### MONITORS ###
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = ,preferred   ,auto   ,auto
source  = ~/.config/hypr/monitors.conf   # Device specific, not git tracked

### MY PROGRAMS ###
source  = ~/.config/hypr/programs.conf

### AUTOSTART ###
source  = ~/.config/hypr/autostart.conf 

### ENVIRONMENT VARIABLES ###
source  = ~/.config/hypr/env.conf 

### LOOK AND FEEL ###
source  = ~/.config/hypr/style.conf 
source  = ~/.config/hypr/animations.conf

### INPUT ###
source  = ~/.config/hypr/input.conf

### KEYBINDINGS ###
source  = ~/.config/hypr/keybinds.conf

### WINDOWS AND WORKSPACES ###
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/workspaces.conf  # Device specific, not git tracked

### LAYOUTS ###
source  = ~/.config/hypr/layout.conf


### MISC ###
# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vrr = 1
    focus_on_activate = true
    new_window_takes_over_fullscreen = 2
}




