# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = false # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
    force_split = 2
    
    #smart_split = 1
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    #new_status = master
    smart_resizing = true
    new_on_active = true
    drop_at_cursor = true
    #always_center_master = true
    #orientation = center
}
