# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal    = kitty
$fileManager = dolphin
$menu        = pkill rofi || true && rofi -show drun -theme ~/.config/rofi/launcher/launcher.rasi 

# Default Search Engine for ROFI Search (SUPER S)
$Search_Engine = "https://www.google.com/search?q={}"

# Scripts programs
#$clipboard = ~/.config/rofi/clipboard/launcher.sh
#$shotcut = ~/.config/rofi/shotcut/script.sh
#$wallselect = ~/.config/rofi/wallselect/script.sh
#$wifi = ~/.config/rofi/wifi/wifi.sh
#$launcher = ~/.config/rofi/launcher/laucher.sh

# Apps
#$browser = firefox
$audio = pavucontrol
$lock = hyprlock
#$music = spotify # Change this if necessary
#$terminal-float = alacritty
#$logout-w = wlogout

# extra
#$screenshots = hyprshot -m output -o ~/.local/share/screenshots/
