# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = suppressevent fullscreen, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# windowrule to avoid idle for fullscreen apps
windowrule = idleinhibit fullscreen, fullscreen:1

# kitty
windowrulev2 = size 1200 800, center 1, class:^(kitty)$
windowrulev2 = opacity 0.85 0.75, class:^(kitty)$

windowrulev2 = float, class:(discord)
windowrulev2 = size 1650 950, class:(discord)

windowrulev2 = float, class:(steam)

windowrulev2 = float, class:^(eog)$
windowrulev2 = float, class:^(nwg-look)$

windowrulev2 = float, title:^(Volume Control)$
windowrulev2 = size 900 600, title:^(Volume Control)$

#Centers when floating. Needs exclusions
windowrulev2 = center 1, floating:1, class:negative:^(steam|)$

# Dialogs
windowrule = float, title:^(Open File)(.*)$
windowrule = float, title:^(Select a File)(.*)$
windowrule = float, title:^(Choose wallpaper)(.*)$
windowrule = float, title:^(Open Folder)(.*)$
windowrule = float, title:^(Save As)(.*)$
windowrule = float, title:^(Library)(.*)$
windowrule = float, title:^(File Upload)(.*)$

# layerrule
layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blur, kitty
layerrule = blur, Alacritty
layerrule = ignorezero, kitty
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.1, waybar

#EXPLORE THIS: check JaKooLit dots for tag setting examples
# windowrule move to workspace
#windowrule = workspace 1, tag:email*
#windowrule = workspace 2, tag:browser*
#windowrule = workspace 3, class:^([Tt]hunar)$
#windowrule = workspace 3, tag:projects*
#windowrule = workspace 5, tag:gamestore*
#windowrule = workspace 7, tag:im*
#windowrule = workspace 8, tag:games*
